# GitHub Actions: Build and deploy to Google Cloud Run on push to "main"

name: "Build and Deploy to Cloud Run"

on:
  push:
    branches: [main]

env:
  PROJECT_ID: "med-space-c2eba"
  REGION: "us-central1"
  SERVICE: "medspace-backend"
  WORKLOAD_IDENTITY_PROVIDER: "projects/567161984682/locations/global/workloadIdentityPools/github-pool/providers/github"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Docker Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
          registry: ${{ env.REGION }}-docker.pkg.dev

      - name: Debug Authentication
        run: |
          echo "Service account:"
          gcloud auth list --filter=status:ACTIVE --format="value(account)"
          echo "Checking Artifact Registry access:"
          gcloud artifacts repositories list --location=us-central1

      - name: Build and Push Docker Image
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Output Cloud Run URL
        run: echo ${{ steps.deploy.outputs.url }}
